FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        iproute2 \
        iputils-ping \
        tcpdump \
        python3 \
        python3-scapy \
        net-tools \
        tini \
    && rm -rf /var/lib/apt/lists/*

COPY topology/entrypoint-host.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/usr/bin/tini", "--", "/entrypoint.sh"]
