FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        iproute2 \
        iputils-ping \
        tcpdump \
        frr \
        frr-pythontools \
        net-tools \
        procps \
        jq \
        tini \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i 's/^ospfd=no/ospfd=yes/' /etc/frr/daemons \
    && sed -i 's/^vtysh_enable=no/vtysh_enable=yes/' /etc/frr/daemons \
    && touch /etc/frr/vtysh.conf

COPY topology/entrypoint-router.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/usr/bin/tini", "--", "/entrypoint.sh"]
