frr version 8.4
frr defaults traditional
hostname r3
log syslog informational
service integrated-vtysh-config

interface to-r1
 ip ospf network point-to-point
exit

interface to-r4
 ip ospf network point-to-point
exit

router ospf
 ospf router-id 3.3.3.3
 network 3.3.3.3/32 area 0
 network 10.0.13.0/29 area 0
 network 10.0.34.0/29 area 0
exit
