frr version 8.4
frr defaults traditional
hostname r2
log syslog informational
service integrated-vtysh-config

interface to-r1
 ip ospf network point-to-point
exit

interface to-r4
 ip ospf network point-to-point
exit

router ospf
 ospf router-id 2.2.2.2
 network 2.2.2.2/32 area 0
 network 10.0.12.0/29 area 0
 network 10.0.24.0/29 area 0
exit
