frr version 8.4
frr defaults traditional
hostname r1
log syslog informational
service integrated-vtysh-config

interface to-r2
 ip ospf network point-to-point
exit

interface to-r3
 ip ospf network point-to-point
exit

router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 0
 network 10.0.1.0/24 area 0
 network 10.0.12.0/29 area 0
 network 10.0.13.0/29 area 0
 passive-interface to-h1
exit
