frr version 8.4
frr defaults traditional
hostname r4
log syslog informational
service integrated-vtysh-config

interface to-r2
 ip ospf network point-to-point
exit

interface to-r3
 ip ospf network point-to-point
exit

router ospf
 ospf router-id 4.4.4.4
 network 4.4.4.4/32 area 0
 network 10.0.2.0/24 area 0
 network 10.0.24.0/29 area 0
 network 10.0.34.0/29 area 0
 passive-interface to-h2
exit
